---
# This playbook will add an initial user on Upspin server

- hosts: upspin
  vars_prompt:
    - name: key
      prompt: "Please provide your public SSH key"
      private: no

  tasks:

    - name: Add new user
      shell: |
        sudo su
        useradd -m upspin
        su upspin
        cd $HOME
        mkdir .ssh
        chmod 0700 .ssh
        echo "{{ key }}" > .ssh/authorized_keys
        chmod 0600 .ssh/authorized_keys
        mkdir -p upspin/letsencrypt
      args:
        executable: /bin/bash