---
# Start Upspin server

- name: Wait for port 443 to open
  wait_for:
    host: "{{ ansible_host }}"
    port: 443
    delay: 10
  delegate_to: localhost

- name: Wait for port 80
  wait_for:
    host: "{{ ansible_host }}"
    port: 80
  delegate_to: localhost

- name: Start Upspin server
  shell: upspin setupserver --host="{{config.domain}}.{{config.zone}}" --domain="{{config.domain}}.{{config.zone}}"
  delegate_to: localhost