---
# This playbook will create a new server on OpenStack
# Running on local, using SSO authentication
# You will need to provide all fields in vars/auth_vars.yml

- name: Create a new server
  os_server:
    state: present
    name: upspin
    auth: "{{ auth_vars.auth }}"
    auth_type: v3oidcpassword
    image: Ubuntu 16 LTS
    key_name: "{{ auth_vars.client_key }}"
    auto_ip: true
    security_groups: default,ssh,upspin
    interface: public
    flavor: m1.s2.medium
  register: server

- name: Add new IP to hosts
  add_host:
    name: upspin
    ansible_host: "{{ server.openstack.interface_ip }}"
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3

- name: Wait for port 22 of Upspin to open active connections
  wait_for:
    host: "{{ server.openstack.interface_ip }}"
    port: 22
    delay: 10

- name: Add SSH host key validation
  shell: "ssh-keyscan -H {{ server.openstack.interface_ip }} >> ~/.ssh/known_hosts"