---
# This playbook will delete an instance
# Running on local, using SSO authentication
# You will need to provide all fields in vars/auth_vars.yml

- hosts: localhost
  connection: local
  vars_prompt:
    - name: server_name
      prompt: "Which server (name or ID) do you want to delete?"
      private: no

  tasks:

    - name: Load private authentication varialbles
      include_vars:
        file: ../vars/auth_vars.yml
        name: auth_vars

    - name: Delete an instance by ID
      os_server:
        state: absent
        name: "{{ server_name }}"
        auth: "{{ auth_vars.auth }}"
        auth_type: v3oidcpassword