---
# This playbook will list all the servers in a project
# Running on local, using SSO authentication
# You will need to provide all fields in vars/auth_vars.yml

- hosts: localhost
  connection: local

  tasks:

    - name: Load private authentication varialbles
      include_vars:
        file: ../vars/auth_vars.yml
        name: auth_vars

    - name: List all servers
      os_server_info:
        auth: "{{ auth_vars.auth }}"
        auth_type: v3oidcpassword
        interface: public
        filters:
          vm_state: active
      register: result

    - name: List server names and IDs
      debug:
        msg: "Server ID is {{ item.id }}."
      loop: "{{ result.openstack_servers }}"
      loop_control:
        label: "{{ item.name }}"