---
# Add necessary security groups on OpenStack

- name: Load private authentication varialbles
  include_vars:
    file: ../vars/auth_vars.yml
    name: auth_vars

- name: Add security group for SSH connection
  os_security_group:
    auth: "{{ auth_vars.auth }}"
    auth_type: v3oidcpassword
    name: ssh
    description: SSH connection

- name: Add security rule for SSH port 22
  os_security_group_rule:
    auth: "{{ auth_vars.auth }}"
    auth_type: v3oidcpassword
    security_group: ssh
    protocol: tcp
    remote_ip_prefix: 0.0.0.0/0
    port_range_min: 22
    port_range_max: 22

- name: Add security group for Upspin server
  os_security_group:
    auth: "{{ auth_vars.auth }}"
    auth_type: v3oidcpassword
    name: upspin
    description: Upspin security rules

- name: Add rule for Upspin port 80
  os_security_group_rule:
    auth: "{{ auth_vars.auth }}"
    auth_type: v3oidcpassword
    security_group: upspin
    protocol: tcp
    remote_ip_prefix: 0.0.0.0/0
    port_range_min: 80
    port_range_max: 80

- name: Add rule for Upspin port 443
  os_security_group_rule:
    auth: "{{ auth_vars.auth }}"
    auth_type: v3oidcpassword
    security_group: upspin
    protocol: tcp
    remote_ip_prefix: 0.0.0.0/0
    port_range_min: 443
    port_range_max: 443